import Head from 'next/head'
import Image from 'next/image'
import NavBar from '../components/nav'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coming Soon | Matthew</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      <main className={styles.main}>

        <div className={styles.grid}>
        <div className={styles.card} style={{borderRadius: "50%", maxWidth: "250px", border: "none", padding: "0"}}>
              <Image src="/memoji.png" width="300px" height="300px" alt="Memoji"/>
          </div>

          <div className={styles.card} style={{height: "170px"}}>
            <h2 className={styles.title}>
              My new portfolio is coming soon!
            </h2>
          </div>

        </div>
      </main>

      <footer className={styles.footer}>
        <p> &copy; 2021 Matthew Van Dyke</p>
      </footer>
    </div>
  )
}
